name: deploy-github-pages
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
      - run: npm install
      - run: npm run build
      - run: ls -l build
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'build'
          destination-github-username: 'aritrakoley'
          destination-repository-name: 'aritrakoley.github.io'
          user-email: koley.aritra824@gmail.com
          target-branch: master